// Human critical-path flows from the eng review test plan.
// Exercises interactions: theme toggle persistence, copy-to-clipboard,
// anchor navigation, skip-link, keyboard-only nav, mobile layout.

import { expect, test } from '@playwright/test';
import { checkA11y, injectAxe } from 'axe-playwright';

test.describe('cold HN land → browse principles → theme dark → reload still dark', () => {
  test('landing on / shows hero + principle listing with 8 entries', async ({ page }) => {
    await page.goto('/');
    await expect(page.locator('.hero__title')).toBeVisible();
    const entries = page.locator('.principle-entry');
    await expect(entries).toHaveCount(8);
  });

  test('clicking a principle entry navigates to its detail page', async ({ page }) => {
    await page.goto('/');
    await page.locator('.principle-entry__link[href="/p3"]').click();
    await expect(page).toHaveURL(/\/p3$/);
    await expect(page.locator('h1')).toContainText('Progressive Help Discovery');
  });

  test('theme button cycles to dark and persists across reload via localStorage', async ({ page }) => {
    await page.goto('/');
    const btn = page.locator('[data-theme-cycle]').first();
    // Cycle: system → light → dark.
    await btn.click();
    await btn.click();
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');

    await page.reload();
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
    // data-theme-choice reflects state after reload.
    await expect(page.locator('[data-theme-cycle]').first()).toHaveAttribute('data-theme-choice', 'dark');
  });

  test('cycling back to system clears localStorage and removes data-theme', async ({ page }) => {
    await page.goto('/');
    const btn = page.locator('[data-theme-cycle]').first();
    // system → light → dark → system.
    await btn.click();
    await btn.click();
    await btn.click();
    await expect(page.locator('html')).not.toHaveAttribute('data-theme', /.+/);
    await expect(btn).toHaveAttribute('data-theme-choice', 'system');
  });
});

test.describe('keyboard + a11y', () => {
  test('skip-link is the first focusable and jumps to #main', async ({ page }) => {
    await page.goto('/');
    await page.keyboard.press('Tab');
    const focused = page.locator(':focus');
    await expect(focused).toHaveAttribute('href', '#main');
  });

  // color-contrast is intentionally disabled: axe-core 4.11.2 misresolves
  // CSS variables defined as oklch() through our :root + data-theme cascade
  // (foundation.css), reporting wildly incorrect foreground colors (e.g.
  // #f3f4f6 for what is actually oklch(0.46 0.015 250) → #525960). The
  // rendered colors pass both WCAG 2.1 AA and APCA Lc ≥ 60 — see the
  // self-verification table in docs/research/design/color-analysis.md (regenerated by
  // scripts/design/generate-palette.mjs whenever the palette changes). All
  // other axe rules under wcag2a/wcag2aa remain enabled and gate this PR.
  const AXE_OPTS = {
    detailedReport: false,
    axeOptions: {
      runOnly: { type: 'tag' as const, values: ['wcag2a', 'wcag2aa'] },
      rules: { 'color-contrast': { enabled: false } },
    },
  };

  test('axe: 0 serious/critical violations on /', async ({ page }) => {
    await page.goto('/');
    await injectAxe(page);
    await checkA11y(page, undefined, AXE_OPTS);
  });

  test('axe: 0 serious/critical violations on /p1', async ({ page }) => {
    await page.goto('/p1');
    await injectAxe(page);
    await checkA11y(page, undefined, AXE_OPTS);
  });
});

test.describe('code-copy + anchor-copy', () => {
  // WebKit does not expose clipboard-read / clipboard-write as grantable
  // permissions, so the Clipboard-API assertions can't run there. Real
  // iOS / iPadOS Safari users still hit the `execCommand('copy')` fallback
  // path in src/client/clipboard.ts — Chromium covers the primary path.
  test('copy button on <pre> writes code to clipboard', async ({ page, context, browserName }) => {
    test.skip(browserName === 'webkit', 'WebKit does not support clipboard permission grants');
    await context.grantPermissions(['clipboard-read', 'clipboard-write']);
    // /audit has 4 code blocks. /p3 has none (no shell snippets in p3 prose).
    await page.goto('/audit');
    // The copy button is injected by src/client/clipboard.ts: each <pre> is
    // wrapped in <div class="code-wrap"> and the <button class="copy-button">
    // is appended to the wrap as a SIBLING of <pre> (not a child). Visibility
    // is gated by `:root.js main .code-wrap .copy-button { display: inline-block }`,
    // so we wait for the .js root class added by theme-init.ts before locating.
    await page.locator('html.js').waitFor();
    const button = page.locator('main .code-wrap .copy-button').first();
    await button.scrollIntoViewIfNeeded();
    await button.click();
    const copied = await page.evaluate(() => navigator.clipboard.readText());
    expect(copied.length).toBeGreaterThan(0);
  });

  test('anchor permalink copies canonical URL and updates the hash', async ({ page, context, browserName }) => {
    test.skip(browserName === 'webkit', 'WebKit does not support clipboard permission grants');
    await context.grantPermissions(['clipboard-read', 'clipboard-write']);
    await page.goto('/p3');
    const anchor = page.locator('h1 a.anchor').first();
    await anchor.click();
    await expect(page).toHaveURL(/#p3-progressive-help-discovery$/);
  });

  // Regression guard for #015: heading-anchor chain icon must return after
  // the "Copied" label fades, so deep-link copy works on every click — not
  // just the first one per page load.
  test('heading anchor restores chain svg after Copied flash and supports repeat clicks', async ({
    page,
    context,
    browserName,
  }) => {
    test.skip(browserName === 'webkit', 'WebKit does not support clipboard permission grants');
    await context.grantPermissions(['clipboard-read', 'clipboard-write']);
    await page.goto('/p3');
    const anchor = page.locator('h1 a.anchor').first();
    await expect(anchor.locator('svg')).toHaveCount(1);

    await anchor.click();
    await expect(anchor).toHaveAttribute('data-copy-state', 'copied');
    const firstWrite = await page.evaluate(() => navigator.clipboard.readText());
    expect(firstWrite).toMatch(/#p3-progressive-help-discovery$/);

    // Wait past the 1500ms COPIED_MS fade plus a small buffer.
    await expect(anchor).not.toHaveAttribute('data-copy-state', 'copied', { timeout: 3000 });
    await expect(anchor.locator('svg')).toHaveCount(1);

    // Second click must produce another flash and clipboard write.
    await page.evaluate(() => navigator.clipboard.writeText(''));
    await anchor.click();
    await expect(anchor).toHaveAttribute('data-copy-state', 'copied');
    const secondWrite = await page.evaluate(() => navigator.clipboard.readText());
    expect(secondWrite).toMatch(/#p3-progressive-help-discovery$/);
    await expect(anchor).not.toHaveAttribute('data-copy-state', 'copied', { timeout: 3000 });
    await expect(anchor.locator('svg')).toHaveCount(1);
  });
});

test.describe('principle listing', () => {
  test('index page has a principle listing with 8 entries', async ({ page }) => {
    await page.goto('/');
    const entries = page.locator('.principle-entry');
    await expect(entries).toHaveCount(8);
  });

  test('principle entry links to its detail page', async ({ page }) => {
    await page.goto('/');
    await page.locator('.principle-entry__link[href="/p5"]').click();
    await expect(page).toHaveURL(/\/p5$/);
    await expect(page.locator('h1')).toContainText('Safe Retries');
  });
});

test.describe('shell — grouped nav, hamburger, footer rows', () => {
  test('desktop (1440): grouped nav links inline, hamburger hidden, footer rows present', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 });
    await page.goto('/');
    const nav = page.getByRole('navigation', { name: 'Primary' });
    await expect(nav).toBeVisible();
    await expect(nav.locator('a')).toHaveCount(6);
    await expect(page.locator('.nav-burger')).toBeHidden();
    await expect(page.locator('.site-footer__source')).toBeVisible();
    await expect(page.locator('.site-footer__meta')).toBeVisible();
  });

  test('mobile (390): inline links hidden, hamburger toggles the panel by pointer', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto('/');
    const nav = page.getByRole('navigation', { name: 'Primary' });
    await expect(nav).toBeHidden();
    const burger = page.locator('.nav-burger');
    await expect(burger).toBeVisible();
    // 44px touch target.
    const box = await burger.boundingBox();
    expect(box!.width).toBeGreaterThanOrEqual(44);
    expect(box!.height).toBeGreaterThanOrEqual(44);

    await burger.click();
    await expect(nav).toBeVisible();
    await burger.click();
    await expect(nav).toBeHidden();

    await expect(page.locator('.site-footer__source')).toBeVisible();
    await expect(page.locator('.site-footer__meta')).toBeVisible();
  });

  test('mobile (390): hamburger checkbox is keyboard-operable (Space opens and closes, no JS needed)', async ({
    page,
  }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto('/');
    const nav = page.getByRole('navigation', { name: 'Primary' });
    const cb = page.locator('.nav-burger__cb');
    await cb.focus();
    await page.keyboard.press('Space');
    await expect(nav).toBeVisible();
    // The same focusable control closes the open panel.
    await page.keyboard.press('Space');
    await expect(nav).toBeHidden();
  });

  test('mobile (390): tagline is hidden under 640px', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto('/');
    await expect(page.locator('.site-brand__tag')).toBeHidden();
  });
});

test.describe('footer AI-provider icons', () => {
  // Regression guard for #016: iOS Safari paints inline <svg> with viewBox
  // but no width/height as 0×0. Anchor stays tappable, glyph disappears.
  // The CSS rule on `.ai-summary__link svg` forces a non-zero box.
  test('every footer ai-provider icon has a non-zero rendered bounding box', async ({ page }) => {
    await page.goto('/');
    const svgs = page.locator('.ai-summary__link svg');
    await expect(svgs).toHaveCount(5);
    const count = await svgs.count();
    for (let i = 0; i < count; i++) {
      const box = await svgs.nth(i).boundingBox();
      expect(box, `provider svg #${i} has no bounding box`).not.toBeNull();
      expect(box!.width).toBeGreaterThan(0);
      expect(box!.height).toBeGreaterThan(0);
    }
  });
});
