// Drift guard for src/worker/spec-version.gen.ts.
//
// `src/build/00-spec-version-gen.mjs` regenerates the file from
// `src/data/spec/VERSION` + `content/principles/VERSION`. The build itself
// runs the emitter, but the .gen.ts file is committed so the worker bundle
// can be type-checked without a build step. This test re-runs the emitter
// in memory and asserts the on-disk file matches — so an out-of-date
// committed file fails CI rather than silently shipping a stale triad.

import { describe, expect, test } from 'bun:test';
import { readFile } from 'node:fs/promises';
import { computeExpectedSpecVersionModule } from '../src/build/00-spec-version-gen.mjs';

describe('spec-version-gen drift guard', () => {
  test('src/worker/spec-version.gen.ts matches the VERSION files', async () => {
    const expected = await computeExpectedSpecVersionModule();
    const actual = await readFile(expected.path, 'utf8');
    if (actual !== expected.content) {
      throw new Error(
        `src/worker/spec-version.gen.ts is out of date relative to VERSION files. ` +
          `Run \`bun run build\` (or \`bun src/build/00-spec-version-gen.mjs\`) and commit the result. ` +
          `Expected SPEC_VERSION=${expected.specVersion}, SITE_SPEC_VERSION=${expected.siteSpecVersion}.`,
      );
    }
    expect(actual).toBe(expected.content);
  });

  test('emitter rejects empty VERSION input', async () => {
    // Exercise the readVersion guard via a fixture-free shape: we re-import
    // the module and verify the public renderer rejects invalid input shape.
    const { renderSpecVersionModule } = await import('../src/build/00-spec-version-gen.mjs');
    const content = renderSpecVersionModule({
      specVersion: '1.2.3',
      siteSpecVersion: '1.2.3',
      auditorUrl: 'https://anc.dev/score',
    });
    expect(content).toContain("export const SPEC_VERSION = '1.2.3'");
    expect(content).toContain("export const SITE_SPEC_VERSION = '1.2.3'");
    expect(content).toContain("export const AUDITOR_URL = 'https://anc.dev/score'");
    // The marker comment is load-bearing for the "do not hand-edit" signal.
    expect(content).toContain('GENERATED by src/build/00-spec-version-gen.mjs');
  });
});
