"""Markdown report: eligibility, distribution, per-column stats, leaderboard, and
rank movers. Generic over the registered algorithms and the config knobs."""

from __future__ import annotations

from . import config
from .frame import profile
from .registry import ALGORITHMS


def _ranks(scored: dict[str, dict[str, int]], col: str) -> dict[str, int]:
    ordered = sorted(scored, key=lambda s: scored[s][col], reverse=True)
    out: dict[str, int] = {}
    prev: int | None = None
    rank = 0
    for i, s in enumerate(ordered, 1):
        if scored[s][col] != prev:
            rank, prev = i, scored[s][col]
        out[s] = rank
    return out


def render(cards: dict[str, list[dict]], scored: dict[str, dict[str, int]]) -> str:
    cols = list(ALGORITHMS)
    prod, base = config.PROD_COL, config.BASELINE_COL
    profs = {s: profile(rows) for s, rows in cards.items()}
    r_base, r_prod = _ranks(scored, base), _ranks(scored, prod)
    weights_str = "/".join(str(int(config.PROD_TIER_WEIGHTS[t])) for t in ("must", "should", "may"))
    credit_str = "/".join(str(config.EXEC_CREDIT[k]) for k in ("pass", "warn", "fail", "opt_out"))
    L: list[str] = []
    push = L.append

    push("# Scoring sandbox — schema 0.6, binary-behavior")
    push("")
    push(f"Tools analyzed: {len(cards)} (binary-behavior, schema 0.6). Generated by `scripts/score-sandbox.py`.")
    push("")
    push(
        f"**PROD config:** tier weights MUST/SHOULD/MAY = {weights_str}; "
        f"`opt_out` {'IN' if config.PROD_OPT_OUT_IN_DENOM else 'EXCLUDED FROM'} the denominator; "
        f"exec credit pass/warn/fail/opt_out = {credit_str}; n_a/skip/error excluded."
    )
    push("")
    push("## Configurations")
    push("")
    for a in ALGORITHMS.values():
        push(f"- **{a.name}** — {a.doc}")
    push("")

    push("## Eligibility counts (tools at/above floor)")
    push("")
    push("| Floor | " + " | ".join(cols) + " |")
    push("| --- | " + " | ".join("---:" for _ in cols) + " |")
    for fl in config.FLOORS:
        cells = [str(sum(1 for s in scored if scored[s][c] >= fl)) for c in cols]
        push(f"| >= {fl} | " + " | ".join(cells) + " |")
    push("")

    push("## Distribution by score bucket")
    push("")
    push("| Bucket | " + " | ".join(cols) + " |")
    push("| --- | " + " | ".join("---:" for _ in cols) + " |")
    for lo, hi in config.BUCKETS:
        cells = [str(sum(1 for s in scored if lo <= scored[s][c] <= hi)) for c in cols]
        push(f"| {lo}-{hi} | " + " | ".join(cells) + " |")
    push("")

    push("## Median / min / max per column")
    push("")
    push("| Stat | " + " | ".join(cols) + " |")
    push("| --- | " + " | ".join("---:" for _ in cols) + " |")
    stats = {c: sorted(scored[s][c] for s in scored) for c in cols}
    push("| median | " + " | ".join(str(stats[c][len(stats[c]) // 2]) for c in cols) + " |")
    push("| min | " + " | ".join(str(stats[c][0]) for c in cols) + " |")
    push("| max | " + " | ".join(str(stats[c][-1]) for c in cols) + " |")
    push("")

    push(f"## Per-tool leaderboard (sorted by {prod})")
    push("")
    push("| # | Slug | P/W/F/O/NA/skip | " + " | ".join(cols) + f" | Δrank {base}→{prod} |")
    push("| ---: | --- | :---: | " + " | ".join("---:" for _ in cols) + " | :---: |")
    order = sorted(scored, key=lambda s: (scored[s][prod], scored[s][base]), reverse=True)
    for i, s in enumerate(order, 1):
        p = profs[s]
        prof = (
            f"{p.get('pass', 0)}/{p.get('warn', 0)}/{p.get('fail', 0)}/"
            f"{p.get('opt_out', 0)}/{p.get('n_a', 0)}/{p.get('skip', 0)}"
        )
        d = r_base[s] - r_prod[s]
        arrow = f"▲{d}" if d > 0 else (f"▼{-d}" if d < 0 else "–")
        cells = " | ".join(str(scored[s][c]) for c in cols)
        push(f"| {i} | {s} | {prof} | {cells} | {arrow} |")
    push("")

    push(f"## Biggest rank movers, {base} → {prod}")
    push("")
    push(f"| Slug | {base}% | {prod}% | {base} rank | {prod} rank | Δrank |")
    push("| --- | ---: | ---: | ---: | ---: | :---: |")
    for s in sorted(scored, key=lambda s: r_base[s] - r_prod[s], reverse=True):
        d = r_base[s] - r_prod[s]
        if d == 0:
            continue
        arrow = f"▲{d}" if d > 0 else f"▼{-d}"
        push(f"| {s} | {scored[s][base]} | {scored[s][prod]} | {r_base[s]} | {r_prod[s]} | {arrow} |")
    push("")
    return "\n".join(L)
