// GENERATED by src/build/00-spec-version-gen.mjs — do NOT edit.
// Re-run `bun run build` to regenerate. The drift check in
// tests/spec-version-gen.test.ts fails CI if this file is out of date.
//
// SPEC_VERSION       — from src/data/spec/VERSION (the standard the
//                      Worker scores against).
// SITE_SPEC_VERSION  — from content/principles/VERSION (the principle
//                      copy this site renders).
// ANC_VERSION        — from src/data/anc/VERSION (the currently-published
//                      anc binary release; vendored from agentnative-cli's
//                      Cargo.toml).
// AUDITOR_URL        — production live-scoring surface; moves with anc.dev.

export const SPEC_VERSION = '0.4.0';
export const SITE_SPEC_VERSION = '0.4.0';
export const ANC_VERSION = '0.4.0';
export const AUDITOR_URL = 'https://anc.dev/score';
