#!/usr/bin/env bash
# Download variable woff2 fonts into public/fonts/ and verify sha256 hashes.
#
# Usage:
#   scripts/fonts/download.sh           Downloads both fonts to public/fonts/ and rewrites hashes.txt.
#   scripts/fonts/download.sh --verify  Re-downloads to a tmp dir and checks sha256 against hashes.txt.
#                                       Exits 0 on match, 1 on mismatch. Does not touch public/fonts/.
#
# Both fonts are pinned to upstream git commit SHAs per the project's supply-chain policy
# (DESIGN.md §4.3 "Font supply chain" and ~/.claude/CLAUDE.md "SHA pins, never version/tag pins").
# To bump: look up the new commit SHA via `gh api repos/<owner>/<repo>/commits/HEAD --jq .sha`,
# update the pinned SHA below, re-run this script without --verify, review diffs, commit.
#
# Licenses (both OFL):
#   Uncut Sans      — https://github.com/kaspernordkvist/uncut_sans
#   Monaspace Xenon — https://github.com/githubnext/monaspace

set -euo pipefail

# -----------------------------------------------------------------------------
# Pinned sources (SHA-pinned to upstream commits; bump explicitly to update).
# -----------------------------------------------------------------------------

UNCUT_REPO="kaspernordkvist/uncut_sans"
UNCUT_SHA="b3b42467781e3bd98c68f2d70eba325196e7d9c5"
UNCUT_PATH="Webfonts/UncutSans-Variable.woff2"
UNCUT_DEST="uncut-sans-variable.woff2"

MONASPACE_REPO="githubnext/monaspace"
MONASPACE_SHA="f31794b6e9e65698a062262e2f826f679dcb7070"
MONASPACE_PATH="fonts/Web%20Fonts/Variable%20Web%20Fonts/Monaspace%20Xenon/Monaspace%20Xenon%20Var.woff2"
MONASPACE_DEST="monaspace-xenon-variable.woff2"

# -----------------------------------------------------------------------------
# Paths.
# -----------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
FONTS_DIR="$REPO_ROOT/public/fonts"
HASHES_FILE="$SCRIPT_DIR/hashes.txt"

# -----------------------------------------------------------------------------
# Helpers.
# -----------------------------------------------------------------------------

raw_url() {
  local repo="$1" sha="$2" path="$3"
  echo "https://raw.githubusercontent.com/${repo}/${sha}/${path}"
}

die() {
  echo "error: $*" >&2
  exit 1
}

fetch() {
  local url="$1" out="$2"
  curl --fail --silent --show-error --location --output "$out" "$url"
}

sha256_of() {
  sha256sum "$1" | awk '{print $1}'
}

# -----------------------------------------------------------------------------
# Commands.
# -----------------------------------------------------------------------------

cmd_download() {
  mkdir -p "$FONTS_DIR"
  TMP_DIR="$(mktemp -d)"
  trap 'rm -rf "${TMP_DIR:-}"' EXIT
  local tmp="$TMP_DIR"

  echo "→ Uncut Sans variable (pinned $UNCUT_REPO@${UNCUT_SHA:0:7})"
  fetch "$(raw_url "$UNCUT_REPO" "$UNCUT_SHA" "$UNCUT_PATH")" "$tmp/$UNCUT_DEST"

  echo "→ Monaspace Xenon variable (pinned $MONASPACE_REPO@${MONASPACE_SHA:0:7})"
  fetch "$(raw_url "$MONASPACE_REPO" "$MONASPACE_SHA" "$MONASPACE_PATH")" "$tmp/$MONASPACE_DEST"

  cp "$tmp/$UNCUT_DEST" "$FONTS_DIR/$UNCUT_DEST"
  cp "$tmp/$MONASPACE_DEST" "$FONTS_DIR/$MONASPACE_DEST"

  {
    echo "# sha256 hashes of committed public/fonts/*.woff2 — regenerated by scripts/fonts/download.sh."
    echo "# Verify with: scripts/fonts/download.sh --verify"
    echo ""
    echo "$(sha256_of "$FONTS_DIR/$UNCUT_DEST")  $UNCUT_DEST"
    echo "$(sha256_of "$FONTS_DIR/$MONASPACE_DEST")  $MONASPACE_DEST"
  } > "$HASHES_FILE"

  echo ""
  echo "✓ Fonts downloaded to $FONTS_DIR"
  echo "✓ Hashes written to $HASHES_FILE"
  ls -la "$FONTS_DIR"/*.woff2
}

cmd_verify() {
  [ -f "$HASHES_FILE" ] || die "$HASHES_FILE not found; run without --verify first"

  TMP_DIR="$(mktemp -d)"
  trap 'rm -rf "${TMP_DIR:-}"' EXIT
  local tmp="$TMP_DIR"

  echo "→ Re-downloading Uncut Sans variable to verify..."
  fetch "$(raw_url "$UNCUT_REPO" "$UNCUT_SHA" "$UNCUT_PATH")" "$tmp/$UNCUT_DEST"

  echo "→ Re-downloading Monaspace Xenon variable to verify..."
  fetch "$(raw_url "$MONASPACE_REPO" "$MONASPACE_SHA" "$MONASPACE_PATH")" "$tmp/$MONASPACE_DEST"

  # Build expected-hash map from hashes.txt (skip comments and blanks).
  local expected_uncut expected_mono
  expected_uncut="$(awk -v f="$UNCUT_DEST" '/^[^#]/ && $2 == f { print $1 }' "$HASHES_FILE")"
  expected_mono="$(awk -v f="$MONASPACE_DEST" '/^[^#]/ && $2 == f { print $1 }' "$HASHES_FILE")"

  [ -n "$expected_uncut" ] || die "$UNCUT_DEST missing from $HASHES_FILE"
  [ -n "$expected_mono" ] || die "$MONASPACE_DEST missing from $HASHES_FILE"

  local actual_uncut actual_mono
  actual_uncut="$(sha256_of "$tmp/$UNCUT_DEST")"
  actual_mono="$(sha256_of "$tmp/$MONASPACE_DEST")"

  local ok=0
  if [ "$actual_uncut" = "$expected_uncut" ]; then
    echo "✓ $UNCUT_DEST sha256 matches"
  else
    echo "✗ $UNCUT_DEST sha256 mismatch"
    echo "  expected $expected_uncut"
    echo "  actual   $actual_uncut"
    ok=1
  fi

  if [ "$actual_mono" = "$expected_mono" ]; then
    echo "✓ $MONASPACE_DEST sha256 matches"
  else
    echo "✗ $MONASPACE_DEST sha256 mismatch"
    echo "  expected $expected_mono"
    echo "  actual   $actual_mono"
    ok=1
  fi

  # Also check the committed files on disk match the recorded hashes.
  if [ -f "$FONTS_DIR/$UNCUT_DEST" ]; then
    local disk_uncut disk_mono
    disk_uncut="$(sha256_of "$FONTS_DIR/$UNCUT_DEST")"
    disk_mono="$(sha256_of "$FONTS_DIR/$MONASPACE_DEST")"
    [ "$disk_uncut" = "$expected_uncut" ] || { echo "✗ committed $UNCUT_DEST disagrees with hashes.txt"; ok=1; }
    [ "$disk_mono" = "$expected_mono" ] || { echo "✗ committed $MONASPACE_DEST disagrees with hashes.txt"; ok=1; }
  else
    echo "note: $FONTS_DIR/$UNCUT_DEST not on disk; skipping disk-vs-hashes check"
  fi

  exit $ok
}

# -----------------------------------------------------------------------------
# Dispatch.
# -----------------------------------------------------------------------------

case "${1:-}" in
  --verify) cmd_verify ;;
  "")       cmd_download ;;
  *)        die "unknown argument: $1 (use no args or --verify)" ;;
esac
