#!/usr/bin/env bash
# Sync the coverage-matrix artifact from the agentnative repo.
#
# Source of truth: brettdavies/agentnative:coverage/matrix.json
# Generated by:   anc generate coverage-matrix
#
# Run this after the Rust side bumps the matrix (e.g., new checks or
# registry changes). The Rust CI enforces that the committed artifact
# matches the registry via `anc generate coverage-matrix --check`.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SITE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ANC_ROOT="${ANC_ROOT:-$HOME/dev/agentnative}"

src="$ANC_ROOT/coverage/matrix.json"
dst="$SITE_ROOT/src/data/coverage-matrix.json"

if [[ ! -f "$src" ]]; then
  echo "error: $src not found. Set ANC_ROOT or run from a machine with the agentnative repo." >&2
  exit 1
fi

cp "$src" "$dst"
echo "synced: $src → $dst"
